GRIDCRAFT_WIDTH = 16
GRIDCRAFT_HEIGHT = 16
GRIDCRAFT_VIEW_SIZE = 7
GRIDCRAFT_MAX_STEPS = 500
GRIDCRAFT_NUM_AGENTS = 1

TERRAIN_CLASSES = 3
BLOCK_CLASSES = 4
ENTITY_CLASSES = 4
GRID_CHANNEL_CLASSES = (TERRAIN_CLASSES, BLOCK_CLASSES, ENTITY_CLASSES)
GRID_CELLS = GRIDCRAFT_VIEW_SIZE * GRIDCRAFT_VIEW_SIZE
GRID_FEATURES = GRID_CELLS * sum(GRID_CHANNEL_CLASSES)
SELF_FEATURES = 11
OBS_SIZE = GRID_FEATURES + SELF_FEATURES

ACTION_SIZE = 15
Z_SIZE = 32
RNN_SIZE = 128
NUM_MIXTURE = 5
CONTROLLER_INPUT_SIZE = Z_SIZE + RNN_SIZE
