#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

PYTHON_BIN="${PYTHON_BIN:-../.venv/bin/python}"

# Scientific target.
BASELINE_ID="${BASELINE_ID:-B00_model-free-control}"
NUM_AGENTS="${NUM_AGENTS:-3}"
SEEDS="${SEEDS:-1 2 3}"
MODEL_FREE_DOWNSTREAM_ALGO="${MODEL_FREE_DOWNSTREAM_ALGO:-masac}"

# Force the policy backbone under study.
MARL_MODEL="${MARL_MODEL:-lstm}"
MARL_HPO_MODEL="${MARL_HPO_MODEL:-$MARL_MODEL}"
MARL_HPO_REQUIRED_MODEL_TYPE="${MARL_HPO_REQUIRED_MODEL_TYPE:-$MARL_MODEL}"
MARL_LSTM_LAYERS="${MARL_LSTM_LAYERS:-1}"
MARL_LSTM_DROPOUT="${MARL_LSTM_DROPOUT:-0.0}"
MARL_LSTM_COMPILE="${MARL_LSTM_COMPILE:-0}"

# HPO controls.
FORCE_MARL_HPO="${FORCE_MARL_HPO:-0}"
MARL_HPO_FAMILIES="${MARL_HPO_FAMILIES:-masac_core}"
MARL_HPO_SEEDS="${MARL_HPO_SEEDS:-1 2 3}"
MARL_HPO_POLICY_EVAL_MODES="${MARL_HPO_POLICY_EVAL_MODES:-deterministic,mode,temp_1.0,temp_0.5,temp_0.25,temp_0.1,sampled}"
MARL_HPO_POLICY_EVAL_EPISODES="${MARL_HPO_POLICY_EVAL_EPISODES:-8}"

# Stage budgets. These can be overridden independently from the shell.
MARL_HPO_SCREEN_COUNT="${MARL_HPO_SCREEN_COUNT:-8}"
MARL_HPO_PROMOTE_TOP_K="${MARL_HPO_PROMOTE_TOP_K:-3}"
MARL_HPO_FINAL_TOP_K="${MARL_HPO_FINAL_TOP_K:-1}"

MARL_HPO_PROMOTE_NUM_ENVS="${MARL_HPO_PROMOTE_NUM_ENVS:-256}"
MARL_HPO_PROMOTE_FRAMES_PER_BATCH="${MARL_HPO_PROMOTE_FRAMES_PER_BATCH:-4096}"
MARL_HPO_PROMOTE_TRAIN_BATCH_SIZE="${MARL_HPO_PROMOTE_TRAIN_BATCH_SIZE:-512}"
MARL_HPO_PROMOTE_MEMORY_SIZE="${MARL_HPO_PROMOTE_MEMORY_SIZE:-200000}"
MARL_HPO_PROMOTE_MAX_ITERS="${MARL_HPO_PROMOTE_MAX_ITERS:-200}"
MARL_HPO_PROMOTE_EVAL_EVERY_ITERS="${MARL_HPO_PROMOTE_EVAL_EVERY_ITERS:-10}"
MARL_HPO_PROMOTE_EVAL_EPISODES="${MARL_HPO_PROMOTE_EVAL_EPISODES:-4}"

MARL_HPO_FINAL_NUM_ENVS="${MARL_HPO_FINAL_NUM_ENVS:-256}"
MARL_HPO_FINAL_FRAMES_PER_BATCH="${MARL_HPO_FINAL_FRAMES_PER_BATCH:-4096}"
MARL_HPO_FINAL_TRAIN_BATCH_SIZE="${MARL_HPO_FINAL_TRAIN_BATCH_SIZE:-512}"
MARL_HPO_FINAL_MEMORY_SIZE="${MARL_HPO_FINAL_MEMORY_SIZE:-200000}"
MARL_HPO_FINAL_MAX_ITERS="${MARL_HPO_FINAL_MAX_ITERS:-500}"
MARL_HPO_FINAL_EVAL_EVERY_ITERS="${MARL_HPO_FINAL_EVAL_EVERY_ITERS:-20}"
MARL_HPO_FINAL_EVAL_EPISODES="${MARL_HPO_FINAL_EVAL_EPISODES:-4}"

# Final training budget.
FINAL_MARL_MAX_ITERS="${FINAL_MARL_MAX_ITERS:-500}"
FINAL_MARL_NUM_ENVS="${FINAL_MARL_NUM_ENVS:-256}"
FINAL_MARL_FRAMES_PER_BATCH="${FINAL_MARL_FRAMES_PER_BATCH:-4096}"
FINAL_MARL_TRAIN_BATCH_SIZE="${FINAL_MARL_TRAIN_BATCH_SIZE:-512}"
FINAL_MARL_MEMORY_SIZE="${FINAL_MARL_MEMORY_SIZE:-200000}"
FINAL_MARL_EVAL_EVERY_ITERS="${FINAL_MARL_EVAL_EVERY_ITERS:-20}"
FINAL_MARL_EVAL_EPISODES="${FINAL_MARL_EVAL_EPISODES:-4}"
FINAL_MARL_VIDEO_EVERY_ITERS="${FINAL_MARL_VIDEO_EVERY_ITERS:-0}"

# Posthoc hierarchy evaluation.
RUN_POLICY_EVAL="${RUN_POLICY_EVAL:-1}"
EVAL_POLICY_MODES="${EVAL_POLICY_MODES:-deterministic,mode,temp_1.0,temp_0.5,temp_0.25,temp_0.1,sampled}"
EVAL_EPISODES="${EVAL_EPISODES:-16}"
EVAL_MAX_STEPS="${EVAL_MAX_STEPS:-500}"

AUTO_RESOURCE_PROFILE="${AUTO_RESOURCE_PROFILE:-1}"
RESOURCE_PROFILE="${RESOURCE_PROFILE:-spark_max}"
WANDB_FLAG="${WANDB_FLAG:---wandb}"
DRY_RUN="${DRY_RUN:-0}"

run_cmd() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

run_hpo_stage() {
  local stage="$1"
  shift
  echo "=== MARL HPO MASAC+LSTM: stage=${stage} ==="
  run_cmd env \
    AUTO_RESOURCE_PROFILE="$AUTO_RESOURCE_PROFILE" \
    RESOURCE_PROFILE="$RESOURCE_PROFILE" \
    FORCE_MARL_HPO="$FORCE_MARL_HPO" \
    MARL_MODEL="$MARL_MODEL" \
    MARL_HPO_MODEL="$MARL_HPO_MODEL" \
    MARL_HPO_REQUIRED_MODEL_TYPE="$MARL_HPO_REQUIRED_MODEL_TYPE" \
    MARL_HPO_STAGE="$stage" \
    MARL_HPO_FAMILIES="$MARL_HPO_FAMILIES" \
    MARL_HPO_SEEDS="$MARL_HPO_SEEDS" \
    MARL_HPO_POLICY_EVAL_MODES="$MARL_HPO_POLICY_EVAL_MODES" \
    MARL_HPO_POLICY_EVAL_EPISODES="$MARL_HPO_POLICY_EVAL_EPISODES" \
    MARL_LSTM_LAYERS="$MARL_LSTM_LAYERS" \
    MARL_LSTM_DROPOUT="$MARL_LSTM_DROPOUT" \
    MARL_LSTM_COMPILE="$MARL_LSTM_COMPILE" \
    "$@" \
    ./run_marl_hpo_pipeline.bash
}

echo "Gridcraft B00 model-free MASAC+LSTM with mandatory HPO"
echo "  baseline:       ${BASELINE_ID}"
echo "  agents:         ${NUM_AGENTS}"
echo "  final seeds:    ${SEEDS}"
echo "  HPO seeds:      ${MARL_HPO_SEEDS}"
echo "  policy model:   ${MARL_MODEL}"
echo "  LSTM layers:    ${MARL_LSTM_LAYERS}"
echo "  LSTM dropout:   ${MARL_LSTM_DROPOUT}"
echo "  force HPO:      ${FORCE_MARL_HPO}"
echo "  wandb:          ${WANDB_FLAG}"

run_hpo_stage screen \
  MARL_HPO_COUNT="$MARL_HPO_SCREEN_COUNT"

run_hpo_stage promote \
  MARL_HPO_TOP_K="$MARL_HPO_PROMOTE_TOP_K" \
  MARL_HPO_NUM_ENVS="$MARL_HPO_PROMOTE_NUM_ENVS" \
  MARL_HPO_FRAMES_PER_BATCH="$MARL_HPO_PROMOTE_FRAMES_PER_BATCH" \
  MARL_HPO_TRAIN_BATCH_SIZE="$MARL_HPO_PROMOTE_TRAIN_BATCH_SIZE" \
  MARL_HPO_MEMORY_SIZE="$MARL_HPO_PROMOTE_MEMORY_SIZE" \
  MARL_HPO_MAX_ITERS="$MARL_HPO_PROMOTE_MAX_ITERS" \
  MARL_HPO_EVAL_EVERY_ITERS="$MARL_HPO_PROMOTE_EVAL_EVERY_ITERS" \
  MARL_HPO_EVAL_EPISODES="$MARL_HPO_PROMOTE_EVAL_EPISODES"

run_hpo_stage final \
  MARL_HPO_TOP_K="$MARL_HPO_FINAL_TOP_K" \
  MARL_HPO_NUM_ENVS="$MARL_HPO_FINAL_NUM_ENVS" \
  MARL_HPO_FRAMES_PER_BATCH="$MARL_HPO_FINAL_FRAMES_PER_BATCH" \
  MARL_HPO_TRAIN_BATCH_SIZE="$MARL_HPO_FINAL_TRAIN_BATCH_SIZE" \
  MARL_HPO_MEMORY_SIZE="$MARL_HPO_FINAL_MEMORY_SIZE" \
  MARL_HPO_MAX_ITERS="$MARL_HPO_FINAL_MAX_ITERS" \
  MARL_HPO_EVAL_EVERY_ITERS="$MARL_HPO_FINAL_EVAL_EVERY_ITERS" \
  MARL_HPO_EVAL_EPISODES="$MARL_HPO_FINAL_EVAL_EPISODES"

echo "=== Final B00 MASAC+LSTM training/evaluation ==="
for seed in $SEEDS; do
  echo "=== Final B00 seed=${seed} ==="
  run_cmd env \
    AUTO_RESOURCE_PROFILE="$AUTO_RESOURCE_PROFILE" \
    RESOURCE_PROFILE="$RESOURCE_PROFILE" \
    BASELINE_ID="$BASELINE_ID" \
    SEED="$seed" \
    NUM_AGENTS="$NUM_AGENTS" \
    MODEL_FREE_DOWNSTREAM_ALGO="$MODEL_FREE_DOWNSTREAM_ALGO" \
    MARL_MODEL="$MARL_MODEL" \
    MARL_LSTM_LAYERS="$MARL_LSTM_LAYERS" \
    MARL_LSTM_DROPOUT="$MARL_LSTM_DROPOUT" \
    MARL_LSTM_COMPILE="$MARL_LSTM_COMPILE" \
    REUSE_MARL_HPO_CONFIG=1 \
    REQUIRE_MARL_HPO=1 \
    REQUIRED_MARL_HPO_STAGE=final \
    MARL_MAX_ITERS="$FINAL_MARL_MAX_ITERS" \
    MARL_NUM_ENVS="$FINAL_MARL_NUM_ENVS" \
    MARL_FRAMES_PER_BATCH="$FINAL_MARL_FRAMES_PER_BATCH" \
    MARL_TRAIN_BATCH_SIZE="$FINAL_MARL_TRAIN_BATCH_SIZE" \
    MARL_MEMORY_SIZE="$FINAL_MARL_MEMORY_SIZE" \
    MARL_EVAL_EVERY_ITERS="$FINAL_MARL_EVAL_EVERY_ITERS" \
    MARL_EVAL_EPISODES="$FINAL_MARL_EVAL_EPISODES" \
    MARL_VIDEO_EVERY_ITERS="$FINAL_MARL_VIDEO_EVERY_ITERS" \
    WANDB_FLAG="$WANDB_FLAG" \
    ./run_full_benchmarl_baseline.bash
done

if [[ "$RUN_POLICY_EVAL" == "1" ]]; then
  echo "=== Posthoc hierarchy evaluation by temperature ==="
  run_cmd env \
    BASELINE_ID="$BASELINE_ID" \
    SEEDS="$SEEDS" \
    NUM_AGENTS="$NUM_AGENTS" \
    DEVICE="${DEVICE:-cuda}" \
    EVAL_POLICY_MODES="$EVAL_POLICY_MODES" \
    EVAL_EPISODES="$EVAL_EPISODES" \
    EVAL_MAX_STEPS="$EVAL_MAX_STEPS" \
    WANDB_FLAG="$WANDB_FLAG" \
    ./evaluate_trained_policies_hierarchy.bash
else
  echo "[orchestrator] posthoc hierarchy evaluation disabled"
fi

echo "=== Completed B00 MASAC+LSTM HPO + final training campaign ==="
