#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

SEEDS="${SEEDS:-1 2 3}"
NUM_AGENTS="${NUM_AGENTS:-3}"
AUTO_RESOURCE_PROFILE="${AUTO_RESOURCE_PROFILE:-1}"
RESOURCE_PROFILE="${RESOURCE_PROFILE:-spark_max}"
WANDB_FLAG="${WANDB_FLAG:---wandb}"
MARL_MODEL="${MARL_MODEL:-lstm}"
MODEL_FREE_DOWNSTREAM_ALGO="${MODEL_FREE_DOWNSTREAM_ALGO:-masac}"
MODEL_BASED_DOWNSTREAM_ALGO="${MODEL_BASED_DOWNSTREAM_ALGO:-mambpo}"
REUSE_WM_HPO_CONFIG="${REUSE_WM_HPO_CONFIG:-1}"
REUSE_MARL_HPO_CONFIG="${REUSE_MARL_HPO_CONFIG:-1}"
REQUIRE_WM_HPO="${REQUIRE_WM_HPO:-1}"
REQUIRE_MARL_HPO="${REQUIRE_MARL_HPO:-1}"
REQUIRED_WM_HPO_STAGE="${REQUIRED_WM_HPO_STAGE:-final}"
REQUIRED_MARL_HPO_STAGE="${REQUIRED_MARL_HPO_STAGE:-final}"
RUN_POLICY_HIERARCHY_EVAL="${RUN_POLICY_HIERARCHY_EVAL:-1}"
POLICY_HIERARCHY_EVAL_MODES="${POLICY_HIERARCHY_EVAL_MODES:-deterministic,mode,temp_1.0,temp_0.5,temp_0.25,temp_0.1,sampled}"
POLICY_HIERARCHY_EVAL_EPISODES="${POLICY_HIERARCHY_EVAL_EPISODES:-16}"
POLICY_HIERARCHY_EVAL_MAX_STEPS="${POLICY_HIERARCHY_EVAL_MAX_STEPS:-500}"
ANALYSIS_OUT_DIR="${ANALYSIS_OUT_DIR:-analysis_b00_b10_lstm_comparison}"
DRY_RUN="${DRY_RUN:-0}"

echo "Gridcraft B10/MAMBPO+LSTM vs B00/MASAC+LSTM comparison"
echo "  seeds:      ${SEEDS}"
echo "  agents:     ${NUM_AGENTS}"
echo "  MARL model: ${MARL_MODEL}"
echo "  B10 algo:   ${MODEL_BASED_DOWNSTREAM_ALGO}"
echo "  eval modes: ${POLICY_HIERARCHY_EVAL_MODES}"

run_cmd() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

echo "=== Running B10 neural World Model + MAMBPO+LSTM ==="
run_cmd env \
  AUTO_RESOURCE_PROFILE="$AUTO_RESOURCE_PROFILE" \
  RESOURCE_PROFILE="$RESOURCE_PROFILE" \
  BASELINES="B10_neural_k0.0" \
  SEEDS="$SEEDS" \
  NUM_AGENTS="$NUM_AGENTS" \
  MARL_MODEL="$MARL_MODEL" \
  MODEL_FREE_DOWNSTREAM_ALGO="$MODEL_FREE_DOWNSTREAM_ALGO" \
  MODEL_BASED_DOWNSTREAM_ALGO="$MODEL_BASED_DOWNSTREAM_ALGO" \
  REUSE_WM_HPO_CONFIG="$REUSE_WM_HPO_CONFIG" \
  REUSE_MARL_HPO_CONFIG="$REUSE_MARL_HPO_CONFIG" \
  REQUIRE_WM_HPO="$REQUIRE_WM_HPO" \
  REQUIRE_MARL_HPO="$REQUIRE_MARL_HPO" \
  REQUIRED_WM_HPO_STAGE="$REQUIRED_WM_HPO_STAGE" \
  REQUIRED_MARL_HPO_STAGE="$REQUIRED_MARL_HPO_STAGE" \
  RUN_POLICY_HIERARCHY_EVAL="$RUN_POLICY_HIERARCHY_EVAL" \
  POLICY_HIERARCHY_EVAL_MODES="$POLICY_HIERARCHY_EVAL_MODES" \
  POLICY_HIERARCHY_EVAL_EPISODES="$POLICY_HIERARCHY_EVAL_EPISODES" \
  POLICY_HIERARCHY_EVAL_MAX_STEPS="$POLICY_HIERARCHY_EVAL_MAX_STEPS" \
  WANDB_FLAG="$WANDB_FLAG" \
  ./run_benchmarl_requested_baselines_3agents_fast_scientific.bash

echo "=== Aggregating B00/B10 LSTM comparison ==="
run_cmd ../.venv/bin/python analyze_b00_b10_lstm_comparison.py \
  --out-dir "$ANALYSIS_OUT_DIR" \
  --baselines "B00_model-free-control,B10_neural_k0.0" \
  --main-mode "temp_0.5"

echo "=== Completed B10/MAMBPO+LSTM comparison workflow ==="
